name = "Vanillaish"
author = "Chronos"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "78ae4e8e7b4b12436094befd312d4ddf11f985dab8bca67c8ae1f459f0a9bc72"

[versions]
minecraft = "1.20"
quilt = "0.19.0-beta.18"

[options]
acceptable-game-versions = ["1.20"]
