name = "Vanillaish"
author = "Chronos"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "72edb700a8856584fd50d611491733b2a7742d980b3dff6d3497e7f797a8c962"

[versions]
minecraft = "1.20"
quilt = "0.19.0-beta.18"

[options]
acceptable-game-versions = ["1.20"]
