name = "Vanillaish"
author = "Chronos"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "507fd8d05fc7e82654344931c0be73598e7e1738767da716e143a7c8861e1c35"

[versions]
minecraft = "1.20.1"
quilt = "0.19.1-beta.1"

[options]
acceptable-game-versions = ["1.20.1"]
