name = "Vanillaish"
author = "Chronos"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "805529131bc8118266e30f8aae3ac6f9192b6da8bfb9239005612d4da678484c"

[versions]
minecraft = "1.20"
quilt = "0.19.0-beta.18"

[options]
acceptable-game-versions = ["1.20"]
